//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHoi
    {
        public int MaCauHoi { get; set; }
        public string NDCH { get; set; }
        public string A { get; set; }
        public string B { get; set; }
        public string C { get; set; }
        public string D { get; set; }
        public string DapAnDung { get; set; }
        public byte[] HinhAnh { get; set; }
        public Nullable<int> MaKhoi { get; set; }
        public Nullable<int> MaMonHoc { get; set; }
        public Nullable<int> MaChuong { get; set; }
        public Nullable<int> MaBai { get; set; }
        public Nullable<int> DoKho { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> MaGiangVien { get; set; }
    }
}
