//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chuong
    {
        public int MaChuong { get; set; }
        public string TenChuong { get; set; }
        public Nullable<int> MaMonHoc { get; set; }
    }
}
