//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeThi
    {
        public int MaDe { get; set; }
        public Nullable<int> NamHoc { get; set; }
        public Nullable<int> MaHienThi { get; set; }
        public string KyThi { get; set; }
        public string HinhThucThi { get; set; }
        public Nullable<int> SoCauHoi { get; set; }
        public Nullable<int> MaMonHoc { get; set; }
        public Nullable<int> MaKhoi { get; set; }
        public Nullable<int> MaLop { get; set; }
        public Nullable<int> MaGiangVien { get; set; }
    }
}
